name: Bug report
description: bug report for OceanBase
title: "[Bug]: "
labels: [bug]
assignees:
  - caifeizhi
body:
  - type: checkboxes
    attributes:
      label: Please check the issue list for the same bug 
      options:
        - label: Please checked issue list and confirm this bug is encountered for the first time.
          required: true
        - label: Please try full text in English and attach precise description.
          required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Environment Details sometimes important 
      value: |
        - OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
        - Hardware parameter:OS type & Compliler & CPU etc. 
        - Others
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Fast Reproduce Steps(Required)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What is the result? picture is allowed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: what you expected.
    validations:
      required: false
  - type: textarea
    attributes:
      label: other information
      description: Error Log or Core stack or Others
    validations:
      required: false
