name: question
description: concise description of the problem.
title: "[Question]: "
labels: [question]
assignees:
  - caifeizhi
body:
  - type: checkboxes
    attributes:
      label: Please check the issue list for the same question
      options:
        - label: Please try full text in English and attach precise description.
          required: true
  - type: markdown
    attributes:
      value: |
        Make sure you have:
        * Searched [GitHub issue](https://github.com/oceanbase/oceanbase/issues)
        * Searched [documentation](https://open.oceanbase.com)
  - type: textarea
    attributes:
      label: Describe your question
      description: better to provide some pictures.
    validations:
      required: true
